repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: detect-private-key
    -   id: pretty-format-json
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
    - id: mypy
      name: mypy (src/)
      files: ^src/
      additional_dependencies:
        - python-dotenv
        - langchain-core
    - id: mypy
      name: mypy (scripts/)
      files: ^scripts/
      additional_dependencies:
        - python-dotenv
        - langchain-core
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.2
    hooks:
      - id: ruff-check
        args: [ --fix ]
      - id: ruff-format
